[package]
name = "edr-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.62.2", features = [
  "Win32_Foundation",
  "Win32_System_Services",
]}

tracing = "0.1"
tracing-subscriber = "0.3"